const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {normalize,exportRules,importRules,protectPrevious,saveAtomic,inside}=require('../src/config.cjs');
const fixture=()=>({Version:1,Destination:'/demo/out',Unclassified:'/demo/review',Enabled:true,Protected:[],ExcludedFolders:['Keep'],Groups:[],Rules:[],Extensions:[],RootCategories:true});
test('upgrade adds the current user Desktop without changing their destinations or exclusions',()=>{const original=fixture(),c=normalize(original,'/user-two/Desktop');assert.equal(c.WatchFolder,'/user-two/Desktop');assert.equal(c.Destination,original.Destination);assert.deepEqual(c.ExcludedFolders,['Keep']);assert.equal(c.Enabled,false);assert.equal(original.Enabled,true);});
test('exports omit all personal paths, exclusion names, startup and run state',()=>{const c=normalize(fixture(),'/demo');c.LaunchAtLogin=true;assert.deepEqual(Object.keys(exportRules(c)).sort(),['Extensions','Groups','RootCategories','Rules','Version']);});
test('imports preserve watcher, destinations, exclusions and protections',()=>{const c=normalize(fixture(),'/demo');c.Protected=['/old'];const imported=importRules(c,{Version:1,Groups:[{Folder:'Research',Aliases:'research'}],Rules:[],Extensions:[],RootCategories:false,WatchFolder:'/attacker',Destination:'/other',ExcludedFolders:[]});assert.equal(imported.WatchFolder,'/demo');assert.equal(imported.Destination,'/demo/out');assert.deepEqual(imported.ExcludedFolders,['Keep']);assert.deepEqual(imported.Protected,['/old']);assert.equal(imported.Enabled,false);});
test('changing destinations retains old destination protection and new exclusions',()=>{const c=normalize(fixture(),'/demo');const n=protectPrevious({...c,WatchFolder:'/new',Destination:'/new/out',ExcludedFolders:['Personal']},c);assert(n.Protected.includes('/demo/out'));assert.deepEqual(n.ExcludedFolders,['Personal']);});
test('path containment uses full components, never a string prefix',()=>{assert(inside('/demo/sub/file','/demo'));assert(!inside('/demolition','/demo'));});
test('settings writes retain a valid backup',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'logicflow-'));try{const p=path.join(root,'settings.json');await saveAtomic(p,{v:1});await saveAtomic(p,{v:2});assert.equal(JSON.parse(await fs.readFile(p)).v,2);assert.equal(JSON.parse(await fs.readFile(p+'.bak')).v,1);}finally{await fs.rm(root,{recursive:true,force:true});}});
