/* LogicFlow | Author: Cisik */
'use strict';
const api=window.logicflow,root=document.querySelector('#app'),modal=document.querySelector('#editor');
let state,draft,page='overview',step=0,setup=true,dirty=false,preview=[],previewReady=false,activity=[],busy=false,timer,progressTimer;
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={overview:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',folder:'<path d="M3 7V5h7l2 3h9v12H3Z"/>',groups:'<rect x="3" y="4" width="7" height="6" rx="1"/><rect x="14" y="4" width="7" height="6" rx="1"/><path d="M6 10v6h12v-6M12 16v4"/>',file:'<path d="M14 3H5v18h14V8ZM14 3v5h5M8 13h8M8 17h5"/>',rules:'<path d="M4 5h16M4 12h16M4 19h16"/><circle cx="8" cy="5" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="19" r="2"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6ZM8 12l3 3 5-6"/>',history:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7M12 7v5l3 2"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',refresh:'<path d="M20 11a8 8 0 0 0-14-5L3 9m0-6v6h6M4 13a8 8 0 0 0 14 5l3-3m0 6v-6h-6"/>',check:'<path d="m5 12 4 4L19 6"/>',edit:'<path d="m15 4 5 5M4 20l5-1L21 7l-5-5L4 14Z"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/>',up:'<path d="m6 15 6-6 6 6"/>',down:'<path d="m6 9 6 6 6-6"/>',play:'<path d="m8 4 12 8-12 8Z"/>',pause:'<path d="M8 4v16M16 4v16"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.folder}</svg>`;
const btn=(text,action,style='',ico='',attrs='')=>`<button type="button" class="btn ${style}" data-action="${action}" ${attrs}>${ico?icon(ico):''}${text}</button>`;
const empty=(title,detail,ico='folder')=>`<div class="empty">${icon(ico)}<strong>${title}</strong><p class="small">${detail}</p></div>`;
const badge=()=>`<span class="status ${state?.running||state?.runOnce?'running':''}"><span class="dot"></span>${state?.runOnce?'Running once':state?.running?'Automatic':'Paused'}</span>`;
const join=(a,b)=>a.replace(/[\\/]$/,'')+(a.includes('\\')?'\\':'/')+b;
const words=s=>s.split(/[;,]/).map(x=>x.trim()).filter(Boolean).join(';');
const nice=s=>s.split(';').join(', ');
function toast(message,error=false){const el=document.querySelector('#toast');el.textContent=message;el.className=error?'error':'';el.hidden=false;clearTimeout(timer);timer=setTimeout(()=>el.hidden=true,error?9000:4000);}
async function perform(fn){if(busy)return;busy=true;root.classList.add('busy');try{await fn();}catch(e){toast(e.message,true);}finally{busy=false;root.classList.remove('busy');}}
async function edited(){dirty=true;previewReady=false;if(state.running||state.runOnce)state=await api.pause();updateStatus();}
function runSummary(){const r=state.lastRun;return r?`Run complete: ${r.Moved} moved, ${r.Skipped} skipped, ${r.Errors} errors. Organizing is paused.`:'';}
function updateStatus(){
 const once=state?.runOnce;
 const seconds=once?.readyAt?Math.max(0,Math.ceil((once.readyAt-Date.now())/1000)):0;
 const note=document.querySelector('#footer-note');
 if(note)note.innerHTML=once?(once.phase==='waiting'?`Checking files · ${seconds}s remaining. Runs once, then stops.`:once.phase==='moving'?'Organizing this batch. Stops when finished.':'Checking this batch…'):dirty?'<strong>Unsaved changes</strong> · Save and preview before running.':state.running?'Automatic organizing checks every 30 seconds.':'Paused · Run Now sorts once. Start automatic keeps checking.';
 const s=document.querySelector('#status-slot');if(s)s.innerHTML=badge();
 const count=document.querySelector('#moved-count');if(count)count.textContent=state.moved;
 const err=document.querySelector('#runtime-error');if(err){err.hidden=!state.lastError;err.textContent=state.lastError;}
 const check=document.querySelector('#last-check');if(check)check.textContent=state.lastCheck?'Last checked '+new Date(state.lastCheck).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'You decide when to run';
 const toggle=document.querySelector('#sort-toggle');
 if(toggle){toggle.dataset.action=once||state.running?'pause':'start';toggle.disabled=once?.phase==='moving';toggle.innerHTML=icon(once?'close':state.running?'pause':'play')+(once?'Cancel run':state.running?'Pause automatic':'Start automatic');}
 const run=document.querySelector('#run-now');if(run)run.disabled=!!once;
 const notice=document.querySelector('#one-run-status');
 if(notice){notice.hidden=!(once||state.lastRun);notice.textContent=once?(once.phase==='waiting'?`Run Now is checking ${once.candidates} item(s) for changes. ${seconds}s remaining. Only this batch will be organized, then scanning stops.`:once.phase==='moving'?'Organizing this batch once…':'Checking the folder…'):runSummary()+(state.lastRun?.Skipped?' Skipped items changed or were not ready. Run again when they are ready.':'');}
 if(once&&!progressTimer)progressTimer=setInterval(updateStatus,1000);
 if(!once&&progressTimer){clearInterval(progressTimer);progressTimer=null;}
}
const sections=[['overview','Overview','overview'],['folders','Folders','folder'],['groups','Name groups','groups'],['categories','File types','file'],['rules','Custom rules','rules'],['excluded','Leave alone','shield'],['transfer','Import & export','download'],['activity','Activity','history']];
function heading(title,desc,action=''){return `<div class="page-head"><div><div class="eyebrow">Your workspace</div><h1>${title}</h1><p>${desc}</p></div>${action?`<div class="actions mt-6">${action}</div>`:''}</div>`;}
function render(){if(setup){renderSetup();return;}const label=sections.find(x=>x[0]===page)[1];root.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><img src="../assets/icon.png" alt="">LogicFlow</div><div class="brand-sub">A place for every file.</div><div class="nav-label">YOUR WORKSPACE</div><nav aria-label="Main navigation">${sections.map(([id,name,i])=>`<button class="nav-item ${page===id?'active':''}" data-page="${id}" ${page===id?'aria-current="page"':''}>${icon(i)}${name}</button>`).join('')}</nav><div class="sidebar-bottom"><strong>LogicFlow ${esc(state.version)}</strong><p class="mt-1">Author: Cisik</p><button class="btn ghost mt-3" data-action="exit">Exit LogicFlow</button></div></aside><div class="main-shell"><header class="topbar"><div class="crumb">Workspace <span>/</span> <b>${label}</b></div><div class="actions"><span class="small muted" id="last-check"></span><span id="status-slot"></span></div></header><main class="content"><div id="runtime-error" class="notice error mb-5" hidden></div>${pageContent()}</main><footer class="footer"><div class="footer-note" id="footer-note"></div><div class="actions">${btn('Save changes','save','','check')}${btn('Start automatic','start','','play','id="sort-toggle"')}${btn('Run Now','run-now','primary','play','id="run-now"')}</div></footer></div></div>`;updateStatus();}
function reason(r){if(r==='Ambiguous top-level name')return 'More than one group matches';if(r.includes('needs one valid'))return 'Date missing or unclear';if(r.startsWith('Extension '))return r.slice(10)+' file';if(r.startsWith('Filename rule: '))return 'Custom rule';return r;}
function pageContent(){switch(page){
case 'overview':return heading('Everything in its place','See where your files will go before anything moves.',btn('Refresh preview','preview','','refresh'))+`<div id="one-run-status" class="notice mb-4" role="status" hidden></div><div class="card watch-card"><div class="folder-icon">${icon('folder')}</div><div class="min-w-0 flex-1"><div class="row-title">Folder to organize</div><div class="path">${esc(draft.WatchFolder)}</div></div>${btn('Change folder','go-folders','ghost')}</div><div class="stats"><div class="card stat"><div class="label">Items in this preview</div><div class="value">${previewReady?preview.length:'—'}</div><div class="caption">Files and whole folders</div></div><div class="card stat"><div class="label">Need a matching rule</div><div class="value">${previewReady?preview.filter(x=>x.Folder===draft.Unclassified).length:'—'}</div><div class="caption">Sent to your review folder</div></div><div class="card stat"><div class="label">Moved this session</div><div class="value" id="moved-count">${state.moved}</div><div class="caption">Since you opened LogicFlow</div></div></div><div class="section-bar"><h2>Upcoming moves</h2><span class="small muted">Previewing never moves files</span></div><div class="table-wrap">${previewReady&&preview.length?`<table><thead><tr><th>Item</th><th>Where it will go</th><th>Why</th></tr></thead><tbody>${preview.map(r=>`<tr><td><div class="name-cell">${icon(r.Type==='File'?'file':'folder')}<span>${esc(r.Name)}</span></div><div class="small muted mt-1">${r.Type==='File'?'File':'Folder · kept together'}</div></td><td><div class="path">${esc(r.Destination)}</div></td><td><span class="tag ${r.Folder===draft.Unclassified?'amber':''}">${esc(reason(r.Reason))}</span></td></tr>`).join('')}</tbody></table>`:empty(previewReady?'Nothing to move right now':'Take a look before you start',previewReady?'Your folder is clear, or its items are protected.':'Refresh the preview to see which items match your rules.','overview')}</div><p class="small muted mt-4">Folders you leave alone and output folders are never reorganized. Items inside other folders are never scanned.</p>`;
case 'folders':return heading('Choose your folders','Choose one folder to organize and two places to put its items.')+foldersView()+`<div class="card mt-4"><label class="choice"><input type="checkbox" id="launch" ${draft.LaunchAtLogin?'checked':''}><span>Open LogicFlow when I sign in<small>It opens in the notification area and starts paused. Use Run Now once, or Start automatic for ongoing checks.</small></span></label></div>`;
case 'groups':return heading('Keep related work together','Optional: put files into named folders before separating them by file type.',btn('Add a group','add-group','primary','plus'))+groupsView();
case 'transfer':return heading('Take your rules with you','Save your sorting rules in one file, then import them on another computer.')+transferView();
case 'categories':return heading('Sort by file type','Give each type of file a folder. Custom rules are checked first.',btn('Add file type','add-category','primary','plus'))+categoriesView();
case 'rules':return heading('Your rules come first','Send items to a folder when their names contain words you choose.',btn('Add a rule','add-rule','primary','plus'))+rulesView();
case 'excluded':return heading('Leave these folders alone','Choose folders you want to keep exactly where they are.',btn('Choose a folder','choose-excluded','primary','plus'))+exclusionsView();
case 'activity':return heading('Recent activity','See what moved and anything that needs your attention.',btn('Refresh','history','','refresh'))+`<div class="table-wrap">${activity.length?`<table><thead><tr><th>Time</th><th>Result</th><th>Item and location</th></tr></thead><tbody>${activity.map(r=>`<tr><td class="small muted">${esc(new Date(r.Time).toLocaleString())}</td><td><span class="tag ${r.Status==='Error'?'amber':''}">${esc({Pending:'Move started',Moved:'Moved',Error:'Needs attention'}[r.Status]||r.Status)}</span></td><td><div class="path">${esc(r.Source)}<br>→ ${esc(r.Destination)}</div>${r.Status==='Error'?`<div class="small mt-2">${esc(r.Detail)}</div>`:''}</td></tr>`).join('')}</tbody></table>`:empty('No activity yet','Completed moves will appear here.','history')}</div><p class="small muted mt-4">Latest 500 entries. Each move has a start and finish entry. If only a start remains, check both locations before moving the item yourself.</p>`;
}}
function transferView(){return `<div class="review-grid"><section class="card"><h2>Export rules</h2><p class="small muted mt-2 mb-4">Save the choices shown in LogicFlow, including any unsaved edits, as a JSON rules file.</p><div class="review-item">${draft.Groups.length} name groups</div><div class="review-item">${draft.Rules.length} custom rules, in their current order</div><div class="review-item">${draft.Extensions.length} file-type folders</div><div class="review-item small muted">File-type sorting without a matching group: ${draft.RootCategories?'On':'Off'}</div>${btn('Export rules','export','primary','download')}</section><section class="card"><h2>Import rules</h2><p class="small muted mt-2 mb-4">Choose a LogicFlow JSON rules file from another computer or a saved copy.</p><p class="small muted mb-4">Review its groups and rule counts before replacing your current sorting choices. Importing pauses organizing.</p>${btn('Import rules','import','primary','folder')}<p class="small muted mt-4">After importing, save your changes and refresh the preview before starting.</p></section></div><div class="notice mt-5">Your watch folder, output folders, folders to leave alone, sign-in choice and activity stay on this computer. Imported rules use the folder locations you selected here.</div><p class="small muted mt-4">To transfer: export here, copy the JSON file to the other computer, then open Import &amp; export there. Import replaces the current groups, custom rules, file types and file-type fallback setting.</p>`;}
function setupImportView(){return `<section class="card mb-5"><div class="section-bar"><div><h2>Already have a rules file?</h2><p class="small muted mt-2">Import your groups, file types and custom rules now.</p></div>${btn('Import rules','import','','folder')}</div></section>`;}
function foldersView(){return `<div class="setting-stack">${[['WatchFolder','Folder to organize','LogicFlow checks only the items directly inside this folder.','watch'],['Destination','Put organized files here','Your groups, file types and custom rule folders will go here.','organized'],['Unclassified','Put other items here','Items without a matching rule go here, ready for you to review.','unclassified']].map(([key,title,help,kind])=>`<section class="card"><h2>${title}</h2><p class="small muted mt-2">${help}</p><div class="path-picker"><div class="path">${esc(draft[key])}</div>${btn('Choose folder','choose-'+kind,'','folder')}</div></section>`).join('')}</div><div class="notice mt-4">Choose separate output folders on the same drive as the folder you organize. Whole folders move together. Changing locations affects future moves only.</div>`;}
function editButtons(type,i){return btn('','edit-'+type,'icon-btn ghost','edit',`data-index="${i}" aria-label="Edit ${type} ${i+1}"`)+btn('','remove-'+type,'icon-btn ghost danger','trash',`data-index="${i}" aria-label="Remove ${type} ${i+1}"`);}
function groupsView(){return `<div class="notice mb-4">For example, a group called “Garden” can send “Garden notes.docx” to Garden → Documents. Leave groups empty to sort by file type only.</div>${draft.Groups.length?`<div class="table-wrap"><table><thead><tr><th>Folder name</th><th>Words to look for</th><th></th></tr></thead><tbody>${draft.Groups.map((g,i)=>`<tr><td>${esc(g.Folder)}</td><td class="muted">${esc(nice(g.Aliases))}</td><td><div class="actions justify-end">${editButtons('group',i)}</div></td></tr>`).join('')}</tbody></table></div>`:empty('No name groups','Files can go straight into their file-type folders.','groups')}<div class="card mt-4"><label class="choice"><input type="checkbox" id="fallback" ${draft.RootCategories?'checked':''}><span>Sort by file type when no group name matches<small>If this is off, items without a matching group go to your review folder.</small></span></label></div>`;}
function categoriesView(){return `<div class="table-wrap">${draft.Extensions.length?`<table><thead><tr><th>Folder name</th><th>File types</th><th></th></tr></thead><tbody>${draft.Extensions.map((c,i)=>`<tr><td><div class="name-cell">${icon('folder')}${esc(c.Folder)}</div></td><td class="muted">${esc(c.Extensions.split(';').join(', '))}</td><td><div class="actions justify-end">${editButtons('category',i)}</div></td></tr>`).join('')}</tbody></table>`:empty('No file types added','Add one, or use custom rules to decide where items go.','file')}</div><p class="small muted mt-4">Enter a simple folder name such as “Reports”. LogicFlow creates it inside your organized-files folder when needed.</p>`;}
function rulesView(){return `<div class="notice mb-4">Rules run from top to bottom, before file types. The first matching rule wins. Use the arrows to change their order.</div>${draft.Rules.length?draft.Rules.map((r,i)=>`<div class="list-row"><div class="rule-number">${i+1}</div><div class="flex-1 min-w-0 rule-summary"><div>Names containing <strong>${esc(nice(r.Words))}</strong></div><div class="small muted">${esc(r.Kind==='Both'?'Files and folders':r.Kind)} → ${esc(r.Scope==='*'?'':r.Scope+' / ')}${esc(r.Subfolder)}${r.Dated?' / month and year':''}</div></div><div class="actions">${btn('','up-rule','icon-btn ghost','up',`data-index="${i}" aria-label="Move rule ${i+1} up" ${i===0?'disabled':''}`)}${btn('','down-rule','icon-btn ghost','down',`data-index="${i}" aria-label="Move rule ${i+1} down" ${i===draft.Rules.length-1?'disabled':''}`)}${editButtons('rule',i)}</div></div>`).join(''):empty('No custom rules yet','Add a rule for names such as “receipt”, “holiday” or “project notes”.','rules')}`;}
function exclusionsView(){return `<div class="card mb-4"><div class="small muted mb-2">Choose folders directly inside</div><div class="path">${esc(draft.WatchFolder)}</div></div>${draft.ExcludedFolders.length?draft.ExcludedFolders.map((name,i)=>`<div class="list-row"><div class="name-cell">${icon('shield')}<span>${esc(name)}</span></div>${btn('Remove','remove-excluded','ghost danger','',`data-index="${i}"`)}</div>`).join(''):empty('No folders selected','Use Choose a folder to keep a folder and everything inside it untouched.','shield')}<p class="small muted mt-4">Your output folders are protected automatically. Files inside any folder are never sorted individually.</p>`;}
const stepNames=['Folders','File types','Custom rules','Leave alone','Review'];
function renderSetup(){const titles=['Where should LogicFlow work?','How would you like to sort files?','Add your own sorting rules','Keep some folders where they are','You are ready to organize'];const captions=['Choose the folder to organize and where its items should go.','Start with these file types. Rename them, add your own, or use optional name groups.','This is optional. Match words in item names before sorting by file type.','This is optional. Choose folders to leave completely untouched.','Check your choices. Nothing moves until you finish setup and click Run Now or Start automatic.'];let body='';
if(step===0)body=foldersView();
if(step===1)body=setupImportView()+`<div class="section-bar"><h2>File-type folders</h2>${btn('Add file type','add-category','','plus')}</div>${categoriesView()}<div class="section-bar"><h2>Optional name groups</h2>${btn('Add a group','add-group','','plus')}</div>${groupsView()}`;
if(step===2)body=`<div class="section-bar"><h2>Custom rules</h2>${btn('Add a rule','add-rule','primary','plus')}</div>${rulesView()}`;
if(step===3)body=`<div class="section-bar"><h2>Folders to leave alone</h2>${btn('Choose a folder','choose-excluded','primary','plus')}</div>${exclusionsView()}`;
if(step===4)body=`<div class="review-grid"><div class="card"><h2 class="mb-4">Your folders</h2>${[['Organize',draft.WatchFolder],['Organized files',draft.Destination],['Other items',draft.Unclassified]].map(([label,v])=>`<div class="review-item"><div class="small muted">${label}</div><div class="path">${esc(v)}</div></div>`).join('')}</div><div class="card"><h2 class="mb-4">Your choices</h2><div class="review-item">${draft.Extensions.length} file-type folders<p class="small muted">${esc(draft.Extensions.map(x=>x.Folder).join(', ')||'None')}</p></div><div class="review-item">${draft.Groups.length} name groups<p class="small muted">${esc(draft.Groups.map(x=>x.Folder).join(', ')||'Sort directly by file type')}</p></div><div class="review-item">${draft.Rules.length} custom rules</div><div class="review-item">${draft.ExcludedFolders.length} folders left alone<p class="small muted">${esc(draft.ExcludedFolders.join(', ')||'Output folders are always protected')}</p></div></div></div><div class="notice mt-5">Setup saves your choices only. You will see a preview before starting.</div>`;
root.innerHTML=`<div class="setup-shell"><header class="setup-header"><div class="brand"><img src="../assets/icon.png" alt="">LogicFlow</div><div class="small muted">SETUP <span class="mx-3">/</span> Author: Cisik</div></header><main class="setup-main"><div class="setup-body"><div class="steps" aria-label="Setup progress">${stepNames.map((n,i)=>`${i?'<span class="step-line"></span>':''}<div class="step ${i===step?'active':i<step?'done':''}" ${i===step?'aria-current="step"':''}><span class="step-number">${i<step?'✓':i+1}</span>${n}</div>`).join('')}</div><div class="setup-title"><div class="eyebrow">Step ${step+1} of 5</div><h1>${titles[step]}</h1><p>${captions[step]}</p></div>${body}</div></main><footer class="setup-foot"><div><div class="actions">${btn('Back','back','ghost','',step===0?'disabled':'')}${btn('Cancel setup','cancel-setup','ghost')}</div>${btn(step===4?'Finish setup':'Continue',step===4?'finish':'next','primary',step===4?'check':'arrow')}</div></footer></div>`;}
function field(label,id,value='',placeholder='',help=''){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" value="${esc(value)}" placeholder="${esc(placeholder)}" autocomplete="off">${help?`<div class="help">${help}</div>`:''}</div>`;}
function showEditor(type,index=-1){const item=index>=0?(type==='group'?draft.Groups:type==='category'?draft.Extensions:draft.Rules)[index]:{};const title=(index>=0?'Edit ':'Add ')+({group:'a name group',category:'a file type',rule:'a custom rule'}[type]);let fields='';
if(type==='group')fields=field('Folder name','item-folder',item.Folder,'e.g. Garden','This folder is created inside your organized-files folder.')+field('Words to look for in file names','item-words',nice(item.Aliases||''),'e.g. garden, plants','Separate different words or phrases with commas. Any one can match.');
if(type==='category')fields=field('Folder name','item-folder',item.Folder,'e.g. Reports','Use a name only. LogicFlow chooses the full location for you.')+field('File types','item-extensions',(item.Extensions||'').split(';').join(', '),'e.g. pdf, docx','Separate types with commas. A dot is optional. For example, PDF files end in .pdf.');
if(type==='rule')fields=field('Words to look for in the name','item-words',nice(item.Words||''),'e.g. receipt, expenses','Separate words or phrases with commas. Any one can match a whole word or phrase.')+`<div class="two-col"><div class="field"><label for="item-kind">Apply this rule to</label><select id="item-kind">${['Files','Folders','Both'].map(k=>`<option value="${k}" ${item.Kind===k?'selected':''}>${k==='Both'?'Files and folders':k}</option>`).join('')}</select></div><div class="field"><label for="item-scope">Limit to a name group</label><select id="item-scope"><option value="*">No limit — all items</option>${draft.Groups.map(g=>`<option value="${esc(g.Folder)}" ${item.Scope===g.Folder?'selected':''}>${esc(g.Folder)}</option>`).join('')}</select><div class="help">If selected, the group must match the item name. The new folder goes inside that group.</div></div></div>`+field('Send matching items to this folder','item-folder',item.Subfolder,'e.g. Receipts','Enter a folder name to create, or choose an existing folder below.')+`<div class="mt-2">${btn('Choose existing folder','browse-rule','ghost','folder')}</div><div class="path mt-2" id="rule-location"></div><label class="choice mt-5"><input type="checkbox" id="item-dated" ${item.Dated?'checked':''}><span>Add a month-and-year folder<small>Read the date from the item name. For example, “receipt 092026.pdf” goes into 092026. Missing or unclear dates go to your review folder.</small></span></label>`;
modal.innerHTML=`${btn('','close-modal','ghost icon-btn modal-close','close','aria-label="Close editor"')}<h2 id="dialog-title">${title}</h2><p class="small muted">You can change this at any time.</p><form id="item-form" data-type="${type}" data-index="${index}">${fields}<div class="inline-error" id="modal-error" role="alert"></div><div class="actions">${btn('Cancel','close-modal','ghost')}<button class="btn primary" type="submit">${index>=0?'Save changes':'Add '+(type==='category'?'file type':type)}</button></div></form>`;modal.showModal();modal.querySelector('input')?.focus();updateRuleLocation();}
function updateRuleLocation(){const loc=modal.querySelector('#rule-location');if(!loc)return;const scope=modal.querySelector('#item-scope').value,folder=modal.querySelector('#item-folder').value.trim();loc.textContent='Will go to: '+join(scope==='*'?draft.Destination:join(draft.Destination,scope),folder||'Folder name');}
modal.addEventListener('input',updateRuleLocation);modal.addEventListener('change',updateRuleLocation);
modal.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,type=form.dataset.type,index=Number(form.dataset.index),candidate=clone(draft);let collection,item;const v=id=>modal.querySelector('#'+id).value.trim();try{
if(type==='group'){collection=candidate.Groups;item={Folder:v('item-folder'),Aliases:words(v('item-words')||v('item-folder'))};if(/[\\/]/.test(item.Folder))throw new Error('Enter one folder name, without slashes.');}
if(type==='category'){collection=candidate.Extensions;item={Folder:v('item-folder'),Extensions:v('item-extensions').split(/[;,\s]+/).filter(Boolean).map(x=>'.'+x.replace(/^\./,'').toLowerCase()).join(';')};}
if(type==='rule'){collection=candidate.Rules;item={Priority:index>=0?collection[index].Priority:collection.length+1,Scope:v('item-scope'),Words:words(v('item-words')),Subfolder:v('item-folder'),Kind:v('item-kind'),Dated:modal.querySelector('#item-dated').checked};}
if(index>=0){if(type==='group'){const old=collection[index].Folder;candidate.Rules.forEach(r=>{if(r.Scope===old)r.Scope=item.Folder;});}collection[index]=item;}else collection.push(item);
candidate.Rules.forEach((r,n)=>r.Priority=n+1);await api.validate(candidate);draft=candidate;await edited();modal.close();render();}catch(err){modal.querySelector('#modal-error').textContent=err.message;}});
modal.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='close-modal')modal.close();if(b.dataset.action==='browse-rule')perform(async()=>{try{const result=await api.chooseFolder('rule',draft,modal.querySelector('#item-scope').value);if(result){modal.querySelector('#item-folder').value=result;updateRuleLocation();}}catch(err){modal.querySelector('#modal-error').textContent=err.message;}});});
function ask(title,message,confirm='Continue'){return new Promise(resolve=>{modal.innerHTML=`<h2 id="dialog-title">${title}</h2><p class="muted mt-3">${message}</p><div class="actions"><button class="btn ghost" id="ask-no">Cancel</button><button class="btn primary" id="ask-yes">${confirm}</button></div>`;let done=false;const finish=v=>{if(done)return;done=true;modal.removeEventListener('cancel',cancel);modal.close();resolve(v);};const cancel=e=>{e.preventDefault();finish(false);};modal.addEventListener('cancel',cancel);modal.querySelector('#ask-no').onclick=()=>finish(false);modal.querySelector('#ask-yes').onclick=()=>finish(true);modal.showModal();});}
async function selectFolder(kind){if(kind==='watch'&&draft.ExcludedFolders.length&&!(await ask('Change the folder to organize?','Your list of folders to leave alone will be cleared. You can choose folders from the new location afterward.','Change folder')))return;const result=await api.chooseFolder(kind,draft);if(!result)return;
if(kind==='excluded'){if(!draft.ExcludedFolders.some(x=>x.toLowerCase()===result.toLowerCase()))draft.ExcludedFolders.push(result);}
else if(kind==='watch'){const old=draft.WatchFolder;if(result.toLowerCase()!==old.toLowerCase()){draft.Protected=[...new Set([...draft.Protected,draft.Destination,draft.Unclassified])];if(draft.Destination===join(old,'Organized Files'))draft.Destination=join(result,'Organized Files');if(draft.Unclassified===join(old,'Unclassified Items'))draft.Unclassified=join(result,'Unclassified Items');draft.WatchFolder=result;draft.ExcludedFolders=[];}}
else draft[kind==='organized'?'Destination':'Unclassified']=result;await edited();render();}
root.addEventListener('change',e=>perform(async()=>{if(e.target.id==='fallback'){draft.RootCategories=e.target.checked;await edited();}if(e.target.id==='launch'){draft.LaunchAtLogin=e.target.checked;await edited();}}));
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.page){page=b.dataset.page;render();if(page==='activity')perform(async()=>{activity=await api.history();render();});return;}const a=b.dataset.action;if(!a)return;perform(async()=>{
if(a==='next'){await api.validate(draft);step++;render();return;}if(a==='back'){step--;render();return;}
if(a==='cancel-setup'){if(await ask('Close setup?','Your setup choices have not been saved. You can start again next time.','Close setup'))await api.exit();return;}
if(a==='finish'){state=await api.save(draft);draft=clone(state.config);dirty=false;setup=false;page='overview';preview=await api.preview(draft);previewReady=true;render();toast('Setup complete. Review the preview before starting.');return;}
if(a==='go-folders'){page='folders';render();return;}if(a.startsWith('choose-')){await selectFolder(a.slice(7));return;}if(a.startsWith('add-')){if(state.running||state.runOnce)state=await api.pause();showEditor(a.slice(4));return;}if(a.startsWith('edit-')){if(state.running||state.runOnce)state=await api.pause();showEditor(a.slice(5),Number(b.dataset.index));return;}
if(a.startsWith('remove-')){const type=a.slice(7),i=Number(b.dataset.index),key={group:'Groups',category:'Extensions',rule:'Rules',excluded:'ExcludedFolders'}[type];if(type==='group'&&draft.Rules.some(r=>r.Scope===draft.Groups[i].Folder)){toast('First change or remove the custom rules that use this group.',true);return;}if(await ask('Remove this '+(type==='excluded'?'exclusion':type)+'?','This changes your sorting choices only. Existing files and folders will stay where they are.','Remove')){draft[key].splice(i,1);await edited();render();}return;}
if(a==='up-rule'||a==='down-rule'){const i=Number(b.dataset.index),j=i+(a==='up-rule'?-1:1);[draft.Rules[i],draft.Rules[j]]=[draft.Rules[j],draft.Rules[i]];draft.Rules.forEach((r,n)=>r.Priority=n+1);await edited();render();return;}
if(a==='save'){state=await api.save(draft);draft=clone(state.config);dirty=false;previewReady=false;render();toast('Changes saved. Refresh the preview before starting.');return;}
if(a==='preview'){preview=await api.preview(draft);previewReady=true;state.running=false;render();toast('Preview updated. No files moved.');return;}
if(a==='pause'){const wasOnce=!!state.runOnce;state=await api.pause();render();if(wasOnce)toast('Run canceled. Organizing is paused.');return;}
if(a==='start'||a==='run-now'){
 const once=a==='run-now',label=once?'Run Now':'Start automatic';
 if(state.running||state.runOnce)state=await api.pause();
 if(dirty||!previewReady){state=await api.save(draft);draft=clone(state.config);dirty=false;preview=await api.preview(draft);previewReady=true;page='overview';render();toast(`Review the updated preview, then click ${label}.`);return;}
 const message=once?'LogicFlow will check this batch for changes for 30 seconds, organize ready items once, then stop. Changed or locked items stay where they are. Automatic organizing will stay off.':'Matching items will move to their new folders. LogicFlow will keep checking every 30 seconds until you pause it.';
 if(await ask(once?'Run once now?':'Start automatic organizing?',message,label)){state=once?await api.runNow():await api.start();if(once)page='overview';render();}
 return;
}
if(a==='history'){activity=await api.history();render();return;}if(a==='export'){if(await api.exportRules(draft))toast('Rules exported. Your personal folder locations were not included.');return;}
if(a==='import'){
 const result=await api.importRules(draft);if(!result)return;
 const c=result.config;
 const summary=`<strong>${esc(result.filename)}</strong><br><br>${c.Groups.length} name groups · ${c.Rules.length} custom rules · ${c.Extensions.length} file-type folders<br><span class="small">Groups: ${esc(c.Groups.map(g=>g.Folder).join(', ')||'None')}<br>Sort by file type without a matching group: ${c.RootCategories?'On':'Off'}</span><br><br>This replaces your current ${draft.Groups.length} groups, ${draft.Rules.length} custom rules and ${draft.Extensions.length} file-type folders, including unsaved edits. Your local folder locations and exclusions stay the same.<br><br>Nothing moves. ${setup?'Finish setup':'Save changes and refresh the preview'} when you are ready.`;
 if(await ask('Use these imported rules?',summary,'Use these rules')){draft=c;await edited();render();toast(setup?'Rules loaded. Continue setup to review and save them.':'Rules loaded. Save changes, then refresh the preview.');}
 return;
}
if(a==='exit'){if(!dirty||await ask('Exit without saving?','Your unsaved changes will be lost. Saved rules and files will stay unchanged.','Exit'))await api.exit();}
});});
async function init(){try{state=await api.state();setup=state.needsSetup;draft=clone(state.config||state.defaults);draft.Rules.sort((a,b)=>Number(a.Priority)-Number(b.Priority));api.onState(s=>{const finished=!!state.runOnce&&!s.runOnce&&!!s.lastRun;state=s;if(finished){previewReady=false;preview=[];render();toast(runSummary(),!!state.lastRun.Errors);}else updateStatus();});render();}catch(e){root.innerHTML=`<div class="p-10"><h1>LogicFlow could not open</h1><p class="muted mt-4">${esc(e.message)}</p></div>`;}}
init();
